#!/usr/bin/env bash
#  ╦ ╦╦╔╦╗╔═╗  ╔╗ ╔═╗╦═╗
#  ╠═╣║ ║║║╣   ╠╩╗╠═╣╠╦╝
#  ╩ ╩╩═╩╝╚═╝  ╚═╝╩ ╩╩╚═
#	Simple script to hide/show polybar
#   Author: vyraan
#	url: https://github.com/vybraan

function hide() {
	
case "${RICETHEME}" in
    i0x5|i0x7|i0x1|i0x11|i0x10)
        polybar-msg cmd hide | bspc config top_padding 5
        ;;
    i0x6|i0x3)
        polybar-msg cmd hide | bspc config bottom_padding 5
        ;;
    i0x9|i0x4)
        polybar-msg cmd hide | bspc config top_padding 5 | bspc config bottom_padding 5
        ;;
    vybraan)
        eww -c "$HOME"/.config/bspwm/rices/vybraan/bar close bar | bspc config left_padding 5
        ;;
    i0x2)
        eww -c "$HOME"/.config/bspwm/rices/i0x2/arin close-all | bspc config top_padding 5
        ;;
    i0x8)
        eww -c "$HOME"/.config/bspwm/rices/i0x8/bar close bar & polybar-msg cmd hide | bspc config top_padding 5
        ;;
    *)
        echo "Error: Something fails dud.."
        ;;
esac
	
}

function unhide() {
	
case "${RICETHEME}" in
	i0x5|i0x7|i0x10)
		polybar-msg cmd show | bspc config top_padding 60
		;;
	i0x1)
		polybar-msg cmd show | bspc config top_padding 55
		;;
	i0x11)
		polybar-msg cmd show | bspc config top_padding 50
		;;
	i0x6)
		polybar-msg cmd show | bspc config bottom_padding 45
		;;
	i0x9)
		polybar-msg cmd show | bspc config top_padding 42 | bspc config bottom_padding 40
		;;
	i0x4)
		polybar-msg cmd show | bspc config top_padding 50 | bspc config bottom_padding 50
		;;
	i0x3)
		polybar-msg cmd show | bspc config bottom_padding 60
		;;
	vybraan)
		eww -c "$HOME"/.config/bspwm/rices/vybraan/bar open bar | bspc config left_padding 80
		;;
	i0x8)
		eww -c "$HOME"/.config/bspwm/rices/i0x8/bar open bar & polybar-msg cmd show | bspc config top_padding 65
		;;
	i0x2)
		eww -c "$HOME"/.config/bspwm/rices/i0x2/arin open-many \
		   search \
		   apps \
		   weather \
		   music \
		   system | bspc config top_padding 60
		;;
	*)
		echo "Error: Something fails dud.."
		;;
esac

}

case $1 in
	-h | --hide | hide)
		hide
		exit;;
	-u | --unhide | unhide)
		unhide
		exit;;
	*) # Invalid option
		echo "Error: Invalid option"
		exit;;
esac

