#!/usr/bin/env bash
#  ╔═╗╦═╗╔═╗╦ ╦  ╦ ╦╔═╗╔╦╗╔═╗╔╦╗╔═╗╔═╗
#  ╠═╣╠╦╝║  ╠═╣  ║ ║╠═╝ ║║╠═╣ ║ ║╣ ╚═╗
#  ╩ ╩╩╚═╚═╝╩ ╩  ╚═╝╩  ═╩╝╩ ╩ ╩ ╚═╝╚═╝
#	Script to check for new updates in arch and AUR. 
#   Author: vybraan
#	url: https://github.com/vybraan

updates=$(($(checkupdates 2> /dev/null | wc -l || echo 0) + $(yay -Qum 2> /dev/null | wc -l || echo 0)))
echo "${updates:-0}"
